<?php

//////////////////////////////////////////////////// Media ///////////////////////////////////////////////////

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
    'key' => 'group_55c37ccf07a61',
    'title' => 'Mashead',
    'fields' => array (
        array (
            'key' => 'field_55c3830771337',
            'label' => 'Masthead',
            'name' => 'featured_masthead',
            'type' => 'flexible_content',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'button_label' => 'Add',
            'min' => 0,
            'max' => 1,
            'layouts' => array (
                array (
                    'key' => '55c382b716c5e',
                    'name' => 'image',
                    'label' => 'Image',
                    'display' => 'block',
                    'sub_fields' => array (
                        array (
                            'key' => 'field_55c3843d71338',
                            'label' => 'Image',
                            'name' => 'image',
                            'type' => 'image',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'id',
                            'preview_size' => 'thumbnail',
                            'library' => 'uploadedTo',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                array (
                    'key' => '55c3846071339',
                    'name' => 'video',
                    'label' => 'Video',
                    'display' => 'row',
                    'sub_fields' => array (
                        array (
                            'key' => 'field_55c384677133a',
                            'label' => 'Video',
                            'name' => 'video',
                            'type' => 'file',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'url',
                            'library' => 'uploadedTo',
                            'min_size' => '',
                            'max_size' => '',
                            'mime_types' => '',
                        ),
                        array (
                            'key' => 'field_55dc4b97ccc36',
                            'label' => 'Secondary image',
                            'name' => 'fallback',
                            'type' => 'image',
                            'instructions' => 'A fall back background image for areas of the site where the full animated masthead isn\'t used',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'id',
                            'preview_size' => 'thumbnail',
                            'library' => 'uploadedTo',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                array (
                    'key' => '55c384807133b',
                    'name' => 'hype',
                    'label' => 'Hype',
                    'display' => 'row',
                    'sub_fields' => array (
                        array (
                            'key' => 'field_55c384867133c',
                            'label' => 'Hype',
                            'name' => 'hype',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'maxlength' => '',
                            'rows' => '',
                            'new_lines' => 'wpautop',
                            'readonly' => 0,
                            'disabled' => 0,
                        ),
                        array (
                            'key' => 'field_55dc4b80ccc35',
                            'label' => 'Secondary image',
                            'name' => 'fallback',
                            'type' => 'image',
                            'instructions' => 'A fall back background image for areas of the site where the full animated masthead isn\'t used',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'id',
                            'preview_size' => 'thumbnail',
                            'library' => 'uploadedTo',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                array (
                    'key' => '55c384937133d',
                    'name' => 'layers',
                    'label' => 'Layers',
                    'display' => 'row',
                    'sub_fields' => array (
                        array (
                            'key' => 'field_55c384fd71340',
                            'label' => 'Layers',
                            'name' => 'layers',
                            'type' => 'flexible_content',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'button_label' => 'Add Layer',
                            'min' => '',
                            'max' => '',
                            'layouts' => array (
                                array (
                                    'key' => '55c38b454ce85',
                                    'name' => 'background',
                                    'label' => 'Background',
                                    'display' => 'block',
                                    'sub_fields' => array (
                                        array (
                                            'key' => 'field_55c38b454ce86',
                                            'label' => 'Image',
                                            'name' => 'image',
                                            'type' => 'image',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array (
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'return_format' => 'id',
                                            'preview_size' => 'thumbnail',
                                            'library' => 'uploadedTo',
                                            'min_width' => '',
                                            'min_height' => '',
                                            'min_size' => '',
                                            'max_width' => '',
                                            'max_height' => '',
                                            'max_size' => '',
                                            'mime_types' => '',
                                        ),
                                        array (
                                            'key' => 'field_55c8919176db3',
                                            'label' => 'Styles',
                                            'name' => 'styles',
                                            'type' => 'text',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array (
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                            'maxlength' => '',
                                            'readonly' => 0,
                                            'disabled' => 0,
                                        ),
                                        array (
                                            'key' => 'field_55ca0bbf83a9a',
                                            'label' => 'Animation',
                                            'name' => 'animation',
                                            'type' => 'select',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array (
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'choices' => array (
                                                'none' => 'None',
                                                'zoomIn' => 'Zoom in',
                                                'zoomOut' => 'Zoom out',
                                                'panUp' => 'Pan up',
                                                'panRight' => 'Pan right',
                                                'panDown' => 'Pan down',
                                                'panLeft' => 'Pan left',
                                            ),
                                            'default_value' => array (
                                                'none' => 'none',
                                            ),
                                            'allow_null' => 0,
                                            'multiple' => 0,
                                            'ui' => 0,
                                            'ajax' => 0,
                                            'placeholder' => '',
                                            'disabled' => 0,
                                            'readonly' => 0,
                                        ),
                                    ),
                                    'min' => 0,
                                    'max' => 1,
                                ),
                                array (
                                    'key' => '55c384a63cc1d',
                                    'name' => 'foreground',
                                    'label' => 'Foreground',
                                    'display' => 'block',
                                    'sub_fields' => array (
                                        array (
                                            'key' => 'field_55c3852e71342',
                                            'label' => 'Image',
                                            'name' => 'image',
                                            'type' => 'image',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array (
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'return_format' => 'id',
                                            'preview_size' => 'thumbnail',
                                            'library' => 'uploadedTo',
                                            'min_width' => '',
                                            'min_height' => '',
                                            'min_size' => '',
                                            'max_width' => '',
                                            'max_height' => '',
                                            'max_size' => '',
                                            'mime_types' => '',
                                        ),
                                        array (
                                            'key' => 'field_55c8919876db4',
                                            'label' => 'Styles',
                                            'name' => 'styles',
                                            'type' => 'text',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array (
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                            'maxlength' => '',
                                            'readonly' => 0,
                                            'disabled' => 0,
                                        ),
                                        array (
                                            'key' => 'field_55ca0bff83a9b',
                                            'label' => 'Animation',
                                            'name' => 'animation',
                                            'type' => 'select',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array (
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'choices' => array (
                                                'none' => 'None',
                                                'zoomIn' => 'Zoom in',
                                                'zoomOut' => 'Zoom out',
                                                'panUp' => 'Pan up',
                                                'panRight' => 'Pan right',
                                                'panDown' => 'Pan down',
                                                'panLeft' => 'Pan left',
                                            ),
                                            'default_value' => array (
                                                'none' => 'none',
                                            ),
                                            'allow_null' => 0,
                                            'multiple' => 0,
                                            'ui' => 0,
                                            'ajax' => 0,
                                            'placeholder' => '',
                                            'disabled' => 0,
                                            'readonly' => 0,
                                        ),
                                    ),
                                    'min' => 0,
                                    'max' => 1,
                                ),
                            ),
                        ),
                        array (
                            'key' => 'field_55dc4a99a49b0',
                            'label' => 'Secondary image',
                            'name' => 'fallback',
                            'type' => 'image',
                            'instructions' => 'A fall back background image for areas of the site where the full animated masthead isn\'t used',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array (
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'id',
                            'preview_size' => 'thumbnail',
                            'library' => 'uploadedTo',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                )
            )
        )
    )
));

endif;


//////////////////////////////////////////////////// Media ///////////////////////////////////////////////////

?>